# Nome do site
title: Josias Souza

# Breve descrição do seu site
description: Aqui você irá encontrar a maioria das informações sobre a minha vida profissional. Alem de outras informações como links para os meus perfis nas redes sociais, algumas fotos de viagens realizadas, e talvez alguns interesses pessoais.

# Idioma do site
language: pt-br

# --- Opções gerais --- #

# Selecione quais links de compartilhamento de rede social serão exibidos nas postagens
share-links-active:
  twitter: true
  facebook: true
  linkedin: true
  vk: false


# Comprimento do trecho da palavra - trunca o trecho para o número especificado de palavras na página de índice
excerpt_length: 13


# --- Misc --- #

# Caractere usado para separar o título e a descrição do site no título do documento HTML
# e título do feed RSS
title-separator: "-"

# Ruby Date Format to show dates of posts
date_format: "%d/%m/%Y"

# Facebook App ID
#fb_app_id: ""


# --- Você não precisa tocar em nada abaixo aqui (mas pode, se quiser) --- #

# Opções de saída (mais informações no site de Jekyll)
timezone: "America/Sao_Paulo"
markdown: kramdown
highlighter: rouge
permalink: /:year/:title/
paginate: 6

kramdown:
  input: GFM

# Valores YAML padrão (mais informações no site de Jekyll)
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: false  # adicionar comentários a todas as postagens do blog
      social-share: true # adicionar botões de compartilhamento de mídia social a todas as postagens do blog
      readtime: true # adicione tempo estimado de leitura em todas as postagens do blog
  -
    scope:
      path: "" # all files
    values:
      layout: "page"
      show-avatar: false

# Excluir esses arquivos do site de produção
exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - screenshot.png
  - docs/

plugins:
  - jekyll-paginate
  - jekyll-sitemap

